=== pagaliv/practicas-PL/tDatosPersonales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Definir la clase tDatosPersonales -->
    <xs:element name="DatosPersonales" type="tDatosPersonales">
        
    </xs:element>
    
    <xs:complexType name= "tDatosPersonales">
        <xs:sequence>
            <xs:element name="Nombre" type="xs:string"/>
            <xs:element name="ApellidoPaterno" type="xs:string"/>
            <xs:element name="ApellidoMaterno" type="xs:string"/>
            <xs:element name="FechaNacimiento" type="xs:date"/>
            <xs:element name="Genero" type="xs:string"/>
            <xs:element name="Direccion">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Calle" type="xs:string"/>
                        <xs:element name="Numero" type="xs:int"/>
                        <xs:element name="Colonia" type="xs:string"/>
                        <xs:element name="Ciudad" type="xs:string"/>
                        <xs:element name="Estado" type="xs:string"/>
                        <xs:element name="CodigoPostal" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Telefono" type="xs:string"/>
            <xs:element name="CorreoElectronico" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    
        <xs:complexType name="tDatosPersonalesE" >
            <xs:complexContent>
                <xs:extension base="tDatosPersonales"> 
                    <xs:sequence>
                        <xs:element name="Origen" type="xs:string"/>
                        <xs:element name="estado_civil" type="xs:string"/>
                    </xs:sequence>                
                </xs:extension>
            </xs:complexContent>
            
        </xs:complexType>
    
</xs:schema>

=== pagaliv/practicas-PL/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<DatosPersonales  xsi:type="tDatosPersonalesE" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/pagaliv/Documents/practicas%20PL/tDatosPersonales.xsd">
    <Nombre></Nombre>
    <ApellidoPaterno></ApellidoPaterno>
    <ApellidoMaterno></ApellidoMaterno>
    <FechaNacimiento>2021-12-04</FechaNacimiento>
    <Genero></Genero>
    <Direccion>
        <Calle></Calle>
        <Numero>12</Numero>
        <Colonia></Colonia>
        <Ciudad></Ciudad>
        <Estado></Estado>
        <CodigoPostal></CodigoPostal>
    </Direccion>
    <Telefono></Telefono>
    <CorreoElectronico></CorreoElectronico>
    <Origen></Origen>
    <estado_civil></estado_civil>
</DatosPersonales>
