=== pagaliv/practicas-PL/practica2/ejercicio2/AlmacenDif.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Definir el tipo complejo 'tAlmacen' -->
    <xs:complexType name="tAlmacen">
        <xs:sequence>
            <xs:element ref="Articulo" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Definir el tipo complejo 'tArticulo' -->
    <xs:complexType name="tArticulo">
        <xs:sequence>
            <xs:element name="autor" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="numeroEj" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Definir el elemento abstracto 'Articulo' -->
    <xs:element name="Articulo" type="tArticulo" abstract="true"/>
    
    <!-- Definir el tipo 'libro' que extiende 'tArticulo' -->
    <xs:complexType name="libro">
        <xs:complexContent>
            <xs:extension base="tArticulo">
                <xs:sequence>
                    <xs:element name="ISBN" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- Definir el elemento 'Libro' que sustituye 'Articulo' -->
    <xs:element name="Libro" type="libro" substitutionGroup="Articulo"/>
    
    <!-- Definir el tipo 'pelicula' que extiende 'tArticulo' -->
    <xs:complexType name="pelicula">
        <xs:complexContent>
            <xs:extension base="tArticulo">
                <xs:sequence>
                    <xs:element name="Origen" type="xs:string"/>
                    <xs:element name="estado_civil" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- Definir el elemento 'Pelicula' que sustituye 'Articulo' -->
    <xs:element name="Pelicula" type="pelicula" substitutionGroup="Articulo"/>
    
    <!-- Definir el tipo 'cd' que extiende 'tArticulo' -->
    <xs:complexType name="cd">
        <xs:complexContent>
            <xs:extension base="tArticulo">
                <xs:sequence>
                    <xs:element name="Discografica" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- Definir el elemento 'CD' que sustituye 'Articulo' -->
    <xs:element name="CD" type="cd" substitutionGroup="Articulo"/>
    
    <!-- Definir el elemento 'Almacen' que hace referencia al tipo 'tAlmacen' -->
    <xs:element name="Almacen" type="tAlmacen"/>
    
</xs:schema>

=== pagaliv/practicas-PL/practica2/ejercicio2/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Almacen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/pagaliv/Documents/GitHub/practicas-PL/practica2/ejercicio2/AlmacenDif.xsd">
    
    <CD>
        <titulo></titulo>
        <numeroEj>3</numeroEj>
        <Discografica></Discografica>
    </CD>
    <Pelicula>
        <titulo></titulo>
        <numeroEj>34</numeroEj>
        <Origen></Origen>
        <estado_civil></estado_civil>
    </Pelicula>
</Almacen>
